package me.nakilex.levelplugin.dialogdemo.market;

import net.kyori.adventure.text.format.NamedTextColor;

/**
 * The 15 goods on sale, row-major to match the slot grid.
 *
 * Icons come from the server's existing {@code icons_pack} textures, so
 * nothing new was added to the pack -- {@code market.yml} only adds glyph
 * entries pointing at files that were already there, at the sizes and ascents
 * this screen needs.
 *
 * <h2>Why each good carries its own advance</h2>
 *
 * Minecraft derives a bitmap glyph's advance from the texture's aspect ratio,
 * and these icons are not all square: {@code mines} is 17x16, {@code anvil}
 * is 16x11 and {@code lottery} is 20x15. The renderer has to know how far the
 * pen moved in order to place the next icon on the same line, so one shared
 * advance constant would leave every icon after a non-square one drifting
 * right -- and the drift accumulates across the row.
 *
 * These values are generated by {@code scratchpad/gen_market_icons.py}, which
 * measures each texture and prints them. Regenerate rather than guessing if
 * an icon is swapped.
 */
public enum MarketGood {

    COAL       ("coal",       "Coal",            64,   12, 18, NamedTextColor.DARK_GRAY,    "common"),
    IRON       ("iron",       "Iron Ore",        32,   45, 24, NamedTextColor.WHITE,        "common"),
    GOLD       ("gold",       "Gold Ore",        16,  120, 17, NamedTextColor.GOLD,         "uncommon"),
    REDSTONE   ("redstone",   "Redstone",        64,   30, 17, NamedTextColor.RED,          "common"),
    LAPIS      ("lapis",      "Lapis",           64,   35, 17, NamedTextColor.BLUE,         "common"),

    DIAMOND    ("diamond",    "Diamond",          8,  400, 17, NamedTextColor.AQUA,         "rare"),
    EMERALD    ("emerald",    "Emerald",          8,  380, 17, NamedTextColor.GREEN,        "rare"),
    KIT        ("kit",        "Miner Kit",        1,  950, 17, NamedTextColor.GRAY,         "uncommon"),
    ENCHANT    ("enchant",    "Enchant Book",    16,  260, 17, NamedTextColor.LIGHT_PURPLE, "rare"),
    TOKEN      ("token",      "Mine Token",      10,  500, 17, NamedTextColor.YELLOW,       "uncommon"),

    KEY_COMMON ("key_common", "Common Key",       5,  300, 17, NamedTextColor.WHITE,        "common"),
    KEY_RARE   ("key_rare",   "Locked Crate",     3,  900, 17, NamedTextColor.AQUA,         "rare"),
    KEY_LEGEND ("key_legend", "Legendary Key",    1, 2500, 17, NamedTextColor.GOLD,         "artifact"),
    BOOSTER    ("booster",    "2x Sell Booster",  1, 1800, 17, NamedTextColor.YELLOW,       "artifact"),
    LOTTERY    ("lottery",    "Lottery Ticket",   1,  250, 22, NamedTextColor.LIGHT_PURPLE, "uncommon");

    /** Matches the {@code market_<key>_<size>_a<n>} glyph ids in market.yml. */
    public final String key;
    public final String label;
    public final int stack;
    public final int price;
    /** Pen advance at size 16; scaled by the renderer for other sizes. */
    public final int advance16;
    public final NamedTextColor color;
    public final String tooltipStyle;

    MarketGood(String key, String label, int stack, int price, int advance16,
               NamedTextColor color, String tooltipStyle) {
        this.key = key;
        this.label = label;
        this.stack = stack;
        this.price = price;
        this.advance16 = advance16;
        this.color = color;
        this.tooltipStyle = tooltipStyle;
    }

    /**
     * Advance at an arbitrary baked size.
     *
     * The 1px inter-glyph gap does not scale with the texture, so it is taken
     * off before scaling and added back after.
     */
    public int advanceAt(int size) {
        return Math.round((advance16 - 1) * (size / 16f)) + 1;
    }
}
