name: LevelPlugin
main: me.nakilex.levelplugin.Main
version: 1.0
author: YourName
api-version: 1.19
description: A simple MMORPG leveling system plugin for Minecraft

commands:
  addpoints:
    description: Grants skill points to a player
    usage: /addpoints <player> <amount>
  addxp:
    description: Grants XP to a player
    usage: /addxp <player> <amount>
  stats:
    description: Opens the stats GUI
    usage: /stats
    permission: none
  additem:
    description: Gives a custom item to a player
    usage: /additem <item_id> <player> <amount>
  setlevel:
    description: Sets a player's level
    usage: /setlevel <player> <level>
  class:
    description: Change your class
    usage: /class <Warrior|Rogue|Archer|Mage>
  addmob:
    description: Spawns custom mobs
    usage: /addmob <mobid> <amount>
  balance:
    description: Shows your coin balance
    usage: /balance
  addcoins:
    description: Adds coins to your balance
    usage: /addcoins <player> <amount>
  blacksmith:
    description: Opens the Blacksmith GUI.
    usage: /blacksmith
  npc:
    description: Main command for managing NPCs.
    usage: /npc <add|remove> <args>
  horse:
    description: Manage your horse
    usage: /horse [reroll]

