name: LevelPlugin
main: me.nakilex.levelplugin.customscreenmenu.CustomScreenMenuPlugin
version: 1.0.0
api-version: 1.20
depend: [BetterHud]
softdepend: [ItemsAdder, PlaceholderAPI, ProtocolLib]
commands:
  cursormenu:
    description: Opens and manages custom screen menus
    usage: /cursormenu <run|stop|items|itemsstop|reload>
permissions:
  cursormenu.run:
    description: Allows using /cursormenu run
    default: true
  cursormenu.stop:
    description: Allows using /cursormenu stop
    default: true
  cursormenu.items:
    description: Allows using /cursormenu items and itemsstop
    default: true
  cursormenu.reload:
    description: Allows reloading menu configurations
    default: op
