hud:
  update-interval-ticks: 1
  placeholder-cache-ttl-ms: 150
  canvas-width-px: 320
  canvas-height-px: 180
  line-height-px: 18
  namespace: betterhud
  output-folder: Nexo/pack/external_packs/BetterHud
  source-textures-folder: plugins/Nexo/pack/external_packs/BetterHud/assets/betterhud/textures
  bossbar:
    lines: 6
    merge: false
  default-modules:
    - fantasy_hud
    - fantasy_hud_compass
    - fantasy_hud_season
    - fantasy_hud_air
