name: LevelPlugin
main: me.nakilex.levelplugin.Main
version: 1.0
author: Nakilex
api-version: 1.19
description: A simple MMORPG leveling system plugin for Minecraft
depend: [ProtocolLib, Citizens, Vault, MythicMobs, PlaceholderAPI]

commands:
  addpoints:
    description: Grants skill points to a player
    usage: /addpoints <player> <amount>
  addxp:
    description: Grants XP to a player
    usage: /addxp <player> <amount>
  stats:
    description: Opens the stats GUI
    usage: /stats
    permission: none
    aliases: [s]
  additem:
    description: Gives a custom item to a player
    usage: /additem <item_id> <player> <amount>
  setlevel:
    description: Sets a player's level
    usage: /setlevel <player> <level>
  class:
    description: Change your class
    usage: /class <Warrior|Rogue|Archer|Mage>
    aliases: [c]
  addmob:
    description: Spawns custom mobs
    usage: /addmob <mobid> <amount>
  balance:
    description: Shows your coin balance
    usage: /balance
    aliases: [b]
  addcoins:
    description: Adds coins to your balance
    usage: /addcoins <player> <amount>
  blacksmith:
    description: Opens the Blacksmith GUI.
    usage: /blacksmith
  horse:
    description: Manage your horse
    usage: /horse [reroll]
    aliases: [h]
  effect:
    description: Toggles the sword circle effect.
    usage: /effect
  ps:
    description: Manage personal storage.
  trade:
    description: Lets you trade with another person
    usage: /trade <Name> | /trade accept | /trade accept <Name> | /trade cancel | /trade deny | /trade deny <Name> | /trade author | /trade version | /trade download | /trade toggle | /trade block | /trade block <Players separated by ","> | /trade unblock | /trade unblock <Players separated by ",">
  party:
    description: Manage your party
    usage: /party <subcommand>
    aliases: [p]
  lootchest:
    description: LootChest management command
    usage: /lootchest <reload|list>
  addpotion:
    description: Gives a player a potion.
    usage: /addpotion <playername> <potion_id>
  duel:
    description: Accepts or Declines a duel request
    usage: /duel <accept|decline>
  salvage:
    description: Opens the Salvage GUI
    usage: /salvage
  merchant:
    description: Opens a merchant GUI.
    usage: /merchant <name>
  spells:
    description: Opens the Spells GUI
    usage: /spells
  dmgnumber:
    description: Toggle floating damage‑number holograms on/off
    usage: /<command>
  dmgchat:
    description: Toggle damage messages in chat
    usage: /<command>
  settings:
    description: Opens the settings menu
    usage: /settings
  addgems:
    description: Give yourself some gems (admin).
  gems:
    description: Check your gem balance.
  gemexchange:
    description: Open the gem exchange GUI
