"""
Generate the market icon glyph entries from the server's existing icons_pack.

No new textures: these files are already in the pack, this only adds glyph
entries that point at them at the sizes and ascents the market needs.

--------------------------------------------------------------------------
The ascent relationship, derived rather than guessed
--------------------------------------------------------------------------

A bitmap glyph's top edge lands at (baseline - ascent), and text lines advance
9px. The window slices pin the constant: they render correctly at ascent 9 on
line L, sitting at art y = L*9. So for a glyph on line L to have its top at art
coordinate y:

    ascent = L*9 + 9 - y

which is independent of the glyph's height. An earlier version of this script
used `size - 1 + remainder`, which for row 1 (y=92, line 10) gave 17 where the
correct value is 7 -- ten pixels high, and it moved the wrong way as the
remainder grew.

That offset is also what made the icons unclickable: a dialog hit-tests a click
to a 9px strip at the line's baseline, so art drawn 10px above its own line
never overlaps its own hit area.

Because a good may be drawn on more than one line (see the renderer -- one
emission per line it overlaps, so the whole face is clickable), the ascents
needed run past the icon height. Generating 1..size+8 covers every line a glyph
of that size can overlap.
"""
import os
from PIL import Image

NEXO = r"C:\Users\noahs\Desktop\Minecraft Servers\1.21.8 XPrison Migration\server\plugins\Nexo"
TEXROOT = os.path.join(NEXO, "pack", "assets", "minecraft", "textures")
OUT_YML = "src/main/resources/resourcepack/nexo/glyphs/market.yml"

# Two sizes rather than five: every extra size multiplies the entry count by
# the full ascent range, and 16/24 are the ones that fit a 25x27 slot.
SIZES = [16, 24]

GOODS = [
    ("COAL",       "icons_pack/mines"),
    ("IRON",       "icons_pack/anvil"),
    ("GOLD",       "icons_pack/coins"),
    ("REDSTONE",   "icons_pack/experience_orb"),
    ("LAPIS",      "icons_pack/mana"),
    ("DIAMOND",    "icons_pack/diamond"),
    ("EMERALD",    "icons_pack/money"),
    ("KIT",        "icons_pack/kits"),
    ("ENCHANT",    "icons_pack/enchantedbook"),
    ("TOKEN",      "icons_pack/token"),
    ("KEY_COMMON", "icons_pack/key"),
    ("KEY_RARE",   "icons_pack/rewards/chestlocked"),
    ("KEY_LEGEND", "icons_pack/crown"),
    ("BOOSTER",    "icons_pack/star"),
    ("LOTTERY",    "icons_pack/lottery"),
]

lines = [
    "# GENERATED by scratchpad/gen_market_icons.py - do not hand-edit.",
    "#",
    "# market_<good>_<size>_a<ascent>: an icons_pack texture at an explicit",
    "# ascent. The renderer picks the id whose ascent puts the icon where it",
    "# wants it:  ascent = line*9 + 9 - y",
    "#",
    "# Ascents run past the icon height because a good is drawn once per text",
    "# line it overlaps, so its whole face is clickable.",
    "",
]

advances = []
missing = []
for name, tex in GOODS:
    src = os.path.join(TEXROOT, *tex.split("/")) + ".png"
    if not os.path.exists(src):
        missing.append((name, src))
        continue
    tw, th = Image.open(src).size
    key = name.lower()
    for s in SIZES:
        for a in range(1, s + 9):
            lines += [
                f"market_{key}_{s}_a{a}:",
                f"  texture: {tex}",
                f"  ascent: {a}",
                f"  height: {s}",
            ]
    advances.append((name, tex, tw, th, round(tw / th * 16) + 1))

open(OUT_YML, "w").write("\n".join(lines) + "\n")
total = sum(s + 8 for s in SIZES) * len(advances)
print(f"wrote {OUT_YML}: {len(advances)} goods x {total // len(advances)} ascent/size "
      f"variants = {total} entries")

if missing:
    print("\n!! MISSING TEXTURES:")
    for name, src in missing:
        print(f"   {name}: {src}")

print("\n--- advances at size 16 (paste into MarketGood) ---")
for name, tex, tw, th, adv in advances:
    note = "" if tw == th else f"   <-- not square ({tw}x{th})"
    print(f"  {name:<11} {tex:<28} advance={adv}{note}")
