"""
Build the empty market stall + the pet showcase glyph.

The stall is sliced into 9px rows exactly like the shop window: a dialog
hit-tests to one text line, and tall art has to become a stack of one-line
slices to be drawn whole. Every slice carries an alpha=1 pixel in its first and
last column so they all report the same advance -- Minecraft derives that from
the rightmost non-transparent pixel, and unpinned slices shear.

The pet is a single texture at several baked heights. Nexo scales a glyph to
its `height`, so one file serves every size; what has to be enumerated is the
ascent, which is not settable from the server. Ascents run 1..height+8 so the
renderer can put the pet on any pixel and on any line it overlaps.

Both source images are cropped to their content bounding box first. The raw
files carry a lot of empty margin, and an uncropped texture makes the glyph's
advance meaningless -- the aspect ratio would describe the margin, not the art.
"""
import os
from PIL import Image

SRC_STALL = r"C:\Users\noahs\Downloads\imagdde.png"
SRC_PET = r"C:\Users\noahs\Downloads\pet.png"
TEX = "src/main/resources/resourcepack/assets/minecraft/textures/market"
OUT_YML = "src/main/resources/resourcepack/nexo/glyphs/market_stall.yml"
LINE = 9

PET_SIZES = [48, 56, 64, 72]

# Minecraft stitches font glyphs into a 256x256 atlas, so a bitmap larger than
# that in either dimension cannot be placed and the glyph is silently dropped --
# the client then draws its missing-character box. The raw pet render is
# 207x272 and hit exactly this: it was the only texture over 256 in the whole
# pack, and the only one that failed to render. 256 itself is fine (the shop
# window slices are 256x9), so the cap is inclusive.
ATLAS_MAX = 256

os.makedirs(f"{TEX}/stall", exist_ok=True)

# ---------------------------------------------------------------- stall
stall = Image.open(SRC_STALL).convert("RGBA")
stall = stall.crop(stall.getbbox())
SW, SH = stall.size
stall.save(f"{TEX}/stall.png")
slices = (SH + LINE - 1) // LINE

for n in range(slices):
    top = n * LINE
    box = stall.crop((0, top, SW, min(top + LINE, SH)))
    if box.size[1] < LINE:
        pad = Image.new("RGBA", (SW, LINE), (0, 0, 0, 0))
        pad.paste(box, (0, 0))
        box = pad
    p = box.load()
    for y in range(LINE):
        for x in (0, SW - 1):
            if p[x, y][3] == 0:
                p[x, y] = (0, 0, 0, 1)
    box.save(f"{TEX}/stall/stall_s{n}.png")

# ------------------------------------------------------------------ pet
pet = Image.open(SRC_PET).convert("RGBA")
pet = pet.crop(pet.getbbox())
if max(pet.size) > ATLAS_MAX:
    scale = ATLAS_MAX / max(pet.size)
    pet = pet.resize((round(pet.size[0] * scale), round(pet.size[1] * scale)), Image.LANCZOS)
PW, PH = pet.size
pet.save(f"{TEX}/pet.png")

lines = [
    "# GENERATED by scratchpad/gen_stall_assets.py - do not hand-edit.",
    f"# stall: {SW}x{SH}, {slices} slices of {LINE}px.",
    f"# pet:   {PW}x{PH}, one texture at {len(PET_SIZES)} baked heights.",
    "#",
    "# ascent = line*9 + 9 - y   (height drops out; see the market docs)",
    "",
]
for n in range(slices):
    lines += [
        f"market_stall_s{n}:",
        f"  texture: market/stall/stall_s{n}",
        f"  ascent: {LINE}",
        f"  height: {LINE}",
    ]
for s in PET_SIZES:
    for a in range(1, s + 9):
        lines += [
            f"market_pet_{s}_a{a}:",
            "  texture: market/pet",
            f"  ascent: {a}",
            f"  height: {s}",
        ]
open(OUT_YML, "w").write("\n".join(lines) + "\n")

# Guard: any texture over the atlas limit is dropped by the client without an
# error, so fail loudly here instead of debugging a blank space in game.
for name, dims in (("stall slice", (SW, LINE)), ("pet", (PW, PH))):
    if max(dims) > ATLAS_MAX:
        raise SystemExit(f"{name} is {dims[0]}x{dims[1]}, over the {ATLAS_MAX}px font atlas limit")

print(f"stall {SW}x{SH} -> {slices} slices   advance = {SW + 1}")
print(f"pet   {PW}x{PH}")
print("pet advance by height:")
for s in PET_SIZES:
    print(f"   {s}px -> {round(PW / PH * s) + 1}  (renders {round(PW / PH * s)}px wide)")
print(f"\nwrote {OUT_YML}: {slices + sum(s + 8 for s in PET_SIZES)} entries")
