import javax.imageio.ImageIO;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/** Builds the /dialogdemo store canvas from store_ui_components.zip. */
public final class GenerateStoreDialogAssets {
    private static final int WIDTH = 730;
    private static final int HEIGHT = 350;
    private static final int CHUNK = 240;
    private static final int LINE = 9;

    public static void main(String[] args) throws Exception {
        Path source = Path.of(args[0]);
        Path textures = Path.of(args[1]);
        Path glyphs = Path.of(args[2]);
        Files.createDirectories(textures);
        BufferedImage canvas = new BufferedImage(WIDTH, HEIGHT, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = canvas.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR);

        // Tabs.
        draw(g, source, "buttons/tab_active_green.png", 0, 0);
        draw(g, source, "buttons/tab_inactive_gray.png", 105, 0);

        // Three compact offers.
        String[] compact = {"1000", "2000", "5000"};
        for (int i = 0; i < compact.length; i++) {
            int x = i * 151;
            draw(g, source, "backgrounds/panel_card_small.png", x, 40);
            draw(g, source, "backgrounds/gem_image_background_small.png", x + 6, 46);
            drawCentered(g, source, "gems/gems_" + compact[i] + ".png", x + 6, 46, 129, 80);
            draw(g, source, "buttons/button_price_small.png", x + 7, 152);
        }

        // Two wide offers.
        String[] wide = {"13000", "30000"};
        for (int i = 0; i < wide.length; i++) {
            int x = i * 225;
            draw(g, source, "backgrounds/panel_card_wide.png", x, 200);
            draw(g, source, "backgrounds/gem_image_background_wide.png", x + 6, 206);
            drawCentered(g, source, "gems/gems_" + wide[i] + ".png", x + 6, 206, 208, 80);
            draw(g, source, "buttons/button_price_wide.png", x + 7, 312);
            draw(g, source, i == 0 ? "buttons/tag_popular_blank.png" : "buttons/tag_value_blank.png",
                    x + (i == 0 ? 140 : 157), 196);
        }

        // Account and cart rail.
        draw(g, source, "backgrounds/panel_info_rectangle.png", 457, 40);
        draw(g, source, "backgrounds/square_icon_background.png", 466, 71);
        draw(g, source, "gems/gems_5000.png", 469, 74, 76, 82);
        draw(g, source, "backgrounds/panel_cart_rectangle.png", 457, 184);
        draw(g, source, "buttons/button_checkout.png", 464, 288);
        draw(g, source, "cart/cart_remove_button.png", 694, 218);
        draw(g, source, "cart/cart_remove_button.png", 694, 247);
        g.dispose();

        StringBuilder yaml = new StringBuilder("# GENERATED by scratchpad/GenerateStoreDialogAssets.java - do not hand-edit.\n");
        int rows = (HEIGHT + LINE - 1) / LINE;
        int chunks = (WIDTH + CHUNK - 1) / CHUNK;
        for (int row = 0; row < rows; row++) {
            int h = Math.min(LINE, HEIGHT - row * LINE);
            for (int chunk = 0; chunk < chunks; chunk++) {
                int w = Math.min(CHUNK, WIDTH - chunk * CHUNK);
                BufferedImage slice = canvas.getSubimage(chunk * CHUNK, row * LINE, w, h);
                BufferedImage out = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
                Graphics2D sg = out.createGraphics();
                sg.drawImage(slice, 0, 0, null);
                sg.dispose();
                pinGlyphWidth(out);
                String id = "store_canvas_r" + row + "_c" + chunk;
                ImageIO.write(out, "png", textures.resolve(id + ".png").toFile());
                yaml.append(id).append(":\n  texture: store/dialog/slices/").append(id)
                        .append("\n  ascent: ").append(h).append("\n  height: ").append(h).append('\n');
            }
        }
        Files.writeString(glyphs, yaml);
    }

    /**
     * Minecraft derives bitmap-glyph advance from the rightmost non-transparent
     * column. Pin both edges with alpha=1 pixels so every row reports its
     * nominal chunk width without adding anything visibly opaque.
     */
    private static void pinGlyphWidth(BufferedImage image) {
        int lastX = image.getWidth() - 1;
        for (int y = 0; y < image.getHeight(); y++) {
            if ((image.getRGB(0, y) >>> 24) == 0) image.setRGB(0, y, 0x01000000);
            if ((image.getRGB(lastX, y) >>> 24) == 0) image.setRGB(lastX, y, 0x01000000);
        }
    }

    private static void draw(Graphics2D g, Path root, String path, int x, int y) throws IOException {
        BufferedImage image = ImageIO.read(root.resolve(path).toFile());
        draw(g, root, path, x, y, image.getWidth() / 2, image.getHeight() / 2);
    }

    private static void draw(Graphics2D g, Path root, String path, int x, int y, int w, int h) throws IOException {
        BufferedImage image = ImageIO.read(root.resolve(path).toFile());
        g.drawImage(image, x, y, w, h, null);
    }

    private static void drawCentered(Graphics2D g, Path root, String path, int x, int y, int w, int h) throws IOException {
        BufferedImage image = ImageIO.read(root.resolve(path).toFile());
        double scale = Math.min(w / (double) image.getWidth(), h / (double) image.getHeight());
        int dw = (int) Math.round(image.getWidth() * scale);
        int dh = (int) Math.round(image.getHeight() * scale);
        g.drawImage(image, x + (w - dw) / 2, y + (h - dh) / 2, dw, dh, null);
    }
}
