import javax.imageio.ImageIO;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/** Builds the compact /dialogdemo store canvas from assets/store_ui. */
public final class GenerateStoreDialogAssets {
    private static final int WIDTH = 730;
    private static final int HEIGHT = 350;
    private static final int CHUNK = 240;
    private static final int LINE = 9;

    private static final int LEFT_X = 32;
    private static final int[] SMALL_X = {LEFT_X, LEFT_X + 134, LEFT_X + 268};
    private static final int[] WIDE_X = {LEFT_X, LEFT_X + 205};
    private static final int TOP_Y = 40;
    private static final int BOTTOM_Y = 188;
    private static final int RAIL_X = 453;
    private static final int CART_Y = 176;

    public static void main(String[] args) throws Exception {
        if (args.length != 3) {
            throw new IllegalArgumentException("Usage: GenerateStoreDialogAssets <assets/store_ui> <slice-output> <glyph-yml>");
        }
        Path source = Path.of(args[0]);
        Path textures = Path.of(args[1]);
        Path glyphs = Path.of(args[2]);
        Files.createDirectories(textures);

        BufferedImage canvas = new BufferedImage(WIDTH, HEIGHT, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = canvas.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR);

        // The v3 assets are authored at 2x Minecraft GUI resolution.
        drawHalf(g, source, "buttons/tab_active_green.png", LEFT_X, 0);
        drawHalf(g, source, "buttons/tab_inactive_gray.png", LEFT_X + 82, 0);

        // Three compact offers.
        String[] compact = {"1000", "2000", "5000"};
        for (int i = 0; i < SMALL_X.length; i++) {
            int x = SMALL_X[i];
            drawHalf(g, source, "backgrounds/panel_card_small.png", x, TOP_Y);
            drawHalf(g, source, "backgrounds/gem_image_background_small.png", x + 5, TOP_Y + 5);
            drawCentered(g, source, "gems/gems_" + compact[i] + ".png", x + 5, TOP_Y + 5, 118, 72);
            drawHalf(g, source, "buttons/button_price_small.png", x + 30, 153);
        }
        drawHalf(g, source, "cart/cart_icon.png", 76, 157);
        drawHalf(g, source, "cart/cart_icon.png", 210, 157);
        drawHalf(g, source, "cart/cart_icon.png", 341, 157);
        drawHalf(g, source, "gems/gem_icon_small.png", 101, 122);
        drawHalf(g, source, "gems/gem_icon_small.png", 235, 122);
        drawHalf(g, source, "gems/gem_icon_small.png", 369, 122);

        // Two compact wide offers.
        String[] wide = {"13000", "30000"};
        for (int i = 0; i < WIDE_X.length; i++) {
            int x = WIDE_X[i];
            drawHalf(g, source, "backgrounds/panel_card_wide.png", x, BOTTOM_Y);
            drawHalf(g, source, "backgrounds/gem_image_background_wide.png", x + 5, BOTTOM_Y + 5);
            drawCentered(g, source, "gems/gems_" + wide[i] + ".png", x + 5, BOTTOM_Y + 5, 190, 72);
            drawHalf(g, source, "buttons/button_price_wide.png", x + 39, 301);
        }
        drawHalf(g, source, "buttons/tag_popular_blank.png", WIDE_X[0] + 124, BOTTOM_Y - 4);
        drawHalf(g, source, "buttons/tag_value_blank.png", WIDE_X[1] + 141, BOTTOM_Y - 4);
        drawHalf(g, source, "cart/cart_icon.png", 109, 305);
        drawHalf(g, source, "cart/cart_icon.png", 314, 305);
        drawHalf(g, source, "gems/gem_icon_small.png", 107, 266);
        drawHalf(g, source, "gems/gem_icon_small.png", 312, 266);

        // Account and cart rail.
        drawHalf(g, source, "backgrounds/panel_info_rectangle.png", RAIL_X, TOP_Y);
        drawHalf(g, source, "backgrounds/square_icon_background.png", RAIL_X + 9, 71);
        draw(g, source, "gems/gems_5000.png", RAIL_X + 12, 74, 68, 74);
        drawHalf(g, source, "gems/gem_icon_small.png", 585, 59);
        drawHalf(g, source, "backgrounds/panel_cart_rectangle.png", RAIL_X, CART_Y);
        drawHalf(g, source, "buttons/button_checkout.png", RAIL_X + 21, 283);
        drawHalf(g, source, "cart/cart_icon.png", 546, 287);
        drawHalf(g, source, "cart/cart_remove_button.png", RAIL_X + 217, 211);
        drawHalf(g, source, "cart/cart_remove_button.png", RAIL_X + 217, 240);
        g.dispose();

        writeSlices(canvas, textures, glyphs);
    }

    private static void writeSlices(BufferedImage canvas, Path textures, Path glyphs) throws IOException {
        StringBuilder yaml = new StringBuilder("# GENERATED by scratchpad/GenerateStoreDialogAssets.java - do not hand-edit.\n");
        int rows = (HEIGHT + LINE - 1) / LINE;
        int chunks = (WIDTH + CHUNK - 1) / CHUNK;
        for (int row = 0; row < rows; row++) {
            int h = Math.min(LINE, HEIGHT - row * LINE);
            for (int chunk = 0; chunk < chunks; chunk++) {
                int w = Math.min(CHUNK, WIDTH - chunk * CHUNK);
                BufferedImage slice = canvas.getSubimage(chunk * CHUNK, row * LINE, w, h);
                BufferedImage out = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
                Graphics2D sg = out.createGraphics();
                sg.drawImage(slice, 0, 0, null);
                sg.dispose();
                pinGlyphWidth(out);
                String id = "store_canvas_r" + row + "_c" + chunk;
                ImageIO.write(out, "png", textures.resolve(id + ".png").toFile());
                yaml.append(id).append(":\n  texture: store/dialog/slices/").append(id)
                        .append("\n  ascent: ").append(h).append("\n  height: ").append(h).append('\n');
            }
        }
        Files.writeString(glyphs, yaml);
    }

    /**
     * Minecraft derives bitmap-glyph advance from the rightmost non-transparent
     * column. Pin both edges with alpha=1 pixels so every row reports its
     * nominal chunk width without adding anything visibly opaque.
     */
    private static void pinGlyphWidth(BufferedImage image) {
        int lastX = image.getWidth() - 1;
        for (int y = 0; y < image.getHeight(); y++) {
            if ((image.getRGB(0, y) >>> 24) == 0) image.setRGB(0, y, 0x01000000);
            if ((image.getRGB(lastX, y) >>> 24) == 0) image.setRGB(lastX, y, 0x01000000);
        }
    }

    private static BufferedImage read(Path path) throws IOException {
        BufferedImage image = ImageIO.read(path.toFile());
        if (image == null) throw new IOException("Unsupported or missing image: " + path);
        return image;
    }

    private static void drawHalf(Graphics2D g, Path root, String path, int x, int y) throws IOException {
        BufferedImage image = read(root.resolve(path));
        g.drawImage(image, x, y, image.getWidth() / 2, image.getHeight() / 2, null);
    }

    private static void draw(Graphics2D g, Path root, String path,
                             int x, int y, int width, int height) throws IOException {
        BufferedImage image = read(root.resolve(path));
        g.drawImage(image, x, y, width, height, null);
    }

    private static void drawCentered(Graphics2D g, Path root, String path,
                                     int x, int y, int width, int height) throws IOException {
        BufferedImage image = read(root.resolve(path));
        double scale = Math.min(width / (double) image.getWidth(), height / (double) image.getHeight());
        int drawnWidth = (int) Math.round(image.getWidth() * scale);
        int drawnHeight = (int) Math.round(image.getHeight() * scale);
        g.drawImage(image, x + (width - drawnWidth) / 2, y + (height - drawnHeight) / 2,
                drawnWidth, drawnHeight, null);
    }
}
