"""
Slice the market shop-window texture into 9px rows, one per text line.

Same technique as the hex node (see docs/native_dialog_demo.md): a dialog
hit-tests a click to one 9px text line and clips a message to the height of
the lines it contains, so tall art has to become a stack of one-line slices
to be both fully visible and fully clickable.

Two details that are easy to get wrong and both bite silently:

* Every slice must report the SAME width. Minecraft derives a bitmap glyph's
  advance from its rightmost non-transparent pixel, and the window's rows
  differ a lot -- the awning is wider than the base. Narrow slices would
  centre differently from wide ones and the window would come out sheared.
  Each slice therefore gets an alpha=1 pixel in its leftmost and rightmost
  column: invisible, but non-transparent to the width calculation.

* Ascent is uniform (9) across slices, not shrinking. Line baselines already
  advance 9px and each slice is 9px tall, so the art reassembles 1:1.
"""
import os
from PIL import Image

SRC = "src/main/resources/resourcepack/assets/minecraft/textures/market/shop_window.png"
OUT_TEX = "src/main/resources/resourcepack/assets/minecraft/textures/market/slices"
OUT_YML = "src/main/resources/resourcepack/nexo/glyphs/market_window.yml"
LINE = 9

img = Image.open(SRC).convert("RGBA")
W, H = img.size
print(f"source {W}x{H}")

os.makedirs(OUT_TEX, exist_ok=True)
slices = (H + LINE - 1) // LINE

for n in range(slices):
    top = n * LINE
    box = img.crop((0, top, W, min(top + LINE, H)))
    # Pad the final short slice to a full line so every glyph is 9px tall and
    # the aspect ratio (and therefore the advance) stays uniform.
    if box.size[1] < LINE:
        padded = Image.new("RGBA", (W, LINE), (0, 0, 0, 0))
        padded.paste(box, (0, 0))
        box = padded

    p = box.load()
    for y in range(LINE):
        for x in (0, W - 1):
            if p[x, y][3] == 0:
                p[x, y] = (0, 0, 0, 1)   # width pin, invisible to the eye

    box.save(f"{OUT_TEX}/shop_window_s{n}.png")

lines = [
    "# GENERATED by scratchpad/slice_shop_window.py - do not hand-edit.",
    f"# {slices} slices of {LINE}px, reassembling the {W}x{H} shop window 1:1.",
    "# Uniform ascent: line baselines already advance 9px per line.",
    "",
]
for n in range(slices):
    lines += [
        f"market_window_s{n}:",
        f"  texture: market/slices/shop_window_s{n}",
        f"  ascent: {LINE}",
        f"  height: {LINE}",
    ]
open(OUT_YML, "w").write("\n".join(lines) + "\n")

print(f"wrote {slices} slices to {OUT_TEX}/")
print(f"wrote {OUT_YML}")
print(f"\nset WINDOW_HEIGHT={H} and WINDOW_SLICES={slices} in MarketDialogDemo "
      f"if they differ from the current 256 / {256 // LINE + 1}")
